### ISSUE TITLE
Improve UI agent output

### ISSUE THREAD

**Issue by ilblackdragon** [nearai/nearai#404]
We want a nicer default theme for UI agent. 
Ideally default should be fitting with our theme of app.near.ai and people can change it later.

**Comment by calebjacob** [comment]
I updated our [react component library](https://github.com/near/pagoda-ui) on NPM to allow agents to use it inline when rendering UI. Here's an example agent that uses the library in its HTML output via `esm.sh`: https://app.near.ai/agents/zavodil.near/swap-agent/latest/source?file=template_react.html

<img width="1166" alt="Screenshot 2024-12-04 at 9 21 27 AM" src="https://github.com/user-attachments/assets/ff2829b4-99d9-49a9-98a8-861598221b46">

This will allow agent authors to render seamless UI for the short term at least. @gabehamilton and myself have also been working on a proposal for handling more UI patterns going forward: https://docs.google.com/document/d/1aPwJkvXZdPrbsKRnb-r5Rcoa1SHgaqtZQlp1tg5BQSk/edit?tab=t.0#heading=h.s80i4qjxt6qz

Going to close this ticket out for now.
