### ISSUE TITLE
Rename Hub to Explorer

### ISSUE THREAD

**Issue by ilblackdragon** [nearai/nearai#503]
We want to rename NEAR AI Hub (the web application) to NEAR AI Explorer.

The NEAR AI ecosystem will have a number of components, like compute nodes and agent runners, decentralized storage and smart contracts that are facilitating various operations, peer-to-peer connectivity and other features. 

NEAR AI Explorer is a single place where researchers, developers and even users can find out all the information they need. This is similar to NEAR Explorer like nearblocks.io and pikespeak.ai that show various information across the ecosystem.

We expect as more features become decentralized, they will merge more into NEAR Protocol itself, and hence will show up in other Explorers as well.

**Comment by ewiner** [comment]
Closing since we went with "Research Hub" instead.
