### ISSUE TITLE
Store benchmark execution details

### ISSUE THREAD

**Issue by mfornet** [nearai/nearai#581]
When we execute a benchmark, it is usually an agent running on multiple tasks individually. It could be interesting to analyze the behavior of the agent/model on successful/unsuccessful tasks and compare the set of tasks solved by different executions. An important first step is to store the trajectory of the execution so that we can inspect it later.

tl;dr: Store the trajectory of the execution of an agent/model on each task of a benchmark.

**Comment by arktoswb** [comment]
I am going to save inputs and outputs of `fn solve` into `solutions.json` inside evaluation registry entries.
Let's also add `nearai evaluation read-solution <registry-entry> [--status=True/False]`

Note: if benchmark dataset is encrypted (#582), then `solutions.json` should be encrypted as well.
