### ISSUE TITLE
Running agent locally writes output to agent code folder

### ISSUE THREAD

**Issue by gabehamilton** [nearai/nearai#632]
Should instead write to /tmp directory.

"/tmp/agent-runner-docker/environment-runs" is specified in https://github.com/nearai/nearai/blob/main/nearai/aws_runner/service.py#L21

**Comment by gabehamilton** [comment]
@arktoswb @PierreLeGuen @zavodil We've changed this many times and ended up back in this state. Is there some reason we're not writing to tmp or was it an accidental regression?

**Comment by zavodil** [comment]
@gabehamilton  Yes, we have to revert that to write into the `tmp` folder. Did you already start implementing that fix? I can work on it too if needed.

**Comment by arktoswb** [comment]
I am not sure what is desired behavior here. Assigning to @zavodil 
But on benchmarks we want agents to write into the same directory (otherwise we will have multithreading conflicts). It's controlled by `change_to_temp_dir` arg.

**Comment by gabehamilton** [comment]
Ok, great, that's exactly the info I needed. I'll set that flag for all the non-benchmarking cases (local & remote agent running).
